# Generated by Django 6.0.5 on 2026-06-01 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='goal_one',
            field=models.TextField(max_length=50),
        ),
        migrations.AlterField(
            model_name='programs',
            name='goal_two',
            field=models.TextField(max_length=50),
        ),
    ]
