# Generated by Django 6.0.5 on 2026-06-02 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0002_alter_programs_goal_one_alter_programs_goal_two'),
    ]

    operations = [
        migrations.AlterField(
            model_name='programs',
            name='profile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
