# Generated by Django 6.0.5 on 2026-06-02 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0003_alter_programs_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='programs',
            name='profile',
        ),
    ]
