# Generated by Django 6.0.5 on 2026-06-04 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('heroes_app', '0004_remove_programs_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gallery',
            name='image',
            field=models.ImageField(upload_to='gallery/'),
        ),
        migrations.AlterField(
            model_name='stories',
            name='profile',
            field=models.ImageField(upload_to='stories/'),
        ),
    ]
